[[redirects]]
  from = "/table"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/operator/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/materials/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/stock"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/backup"
  to = "/index.html"
  status = 200

[[redirects]]
	from = "https://serene-mestorf-73c07a.netlify.com/*"
	to = "https://ark-nights.com/:splat"
	status = 301
	force = true
