[[redirects]]
  from = "/operator"
  to = "/operator"

[[redirects]]
  from = "/info"
  to = "/info"

[[redirects]]
  from = "/backup"
  to = "/backup"

[[redirects]]
	from = "https://serene-mestorf-73c07a.netlify.com/*"
	to = "https://ark-nights.com/:splat"
	status = 301
	force = true
