export const ATTRIBUTES = {
	LEVEL_ELITE_0: 'LEVEL_ELITE_0',
	LEVEL_ELITE_1: 'LEVEL_ELITE_1',
	LEVEL_ELITE_2: 'LEVEL_ELITE_2',
	ELITE_RANK: 'ELITE_RANK',
	SKILL_LEVEL: 'SKILL_LEVEL',
	MASTER_SKILL_1: 'MASTER_SKILL_1',
	MASTER_SKILL_2: 'MASTER_SKILL_2',
	MASTER_SKILL_3: 'MASTER_SKILL_3',
	ADVANCED_EQUIPMENT_1: 'ADVANCED_EQUIPMENT_1',
};
